---
- block:
  - include_tasks: "../../includes/package-with-repo.yml"
    vars:
      apt_source_file: /etc/apt/sources.list.d/google-chrome.list
      apt_source_content: "deb http://dl.google.com/linux/chrome/deb/ stable main"
      apt_key: "https://dl-ssl.google.com/linux/linux_signing_key.pub"
      apt_package: "google-chrome-stable"
  become: yes