---
- hosts: local
  roles:
    - {role: 'packages', tags: 'packages'}
    - {role: 'common', tags: 'common'}
    - {role: 'git', tags: 'git'}
    - {role: 'fish', tags: 'fish'}
    - {role: 'asdf', tags: 'asdf'}
    - {role: 'google-chrome', tags: 'chrome'}
    - {role: 'vscode', tags: 'vscode'}
    - {role: 'riot', tags: 'riot'}
    - {role: 'dropbox', tags: 'dropbox'}
    - {role: 'docker', tags: 'docker'}
    - {role: 'kubectl', tags: 'kubectl'}

  tasks:
    - name: Install ruby gems for jekyll
      tags: ["jekyll"]
      gem:
        name: "{{ item }}"
        user_install: true
        state: present
      loop:
        - bundler
        - jekyll

