---
- hosts: local
  roles:
    - {role: 'packages', tags: 'packages'}
    - {role: 'common', tags: 'common'}
    - {role: 'git', tags: 'git'}
    - {role: 'fish', tags: 'fish'}
    - {role: 'asdf', tags: 'asdf'}
    - {role: 'google-chrome', tags: 'chrome'}
    - {role: 'vscode', tags: 'vscode'}
    - {role: 'riot', tags: 'riot'}
    - {role: 'dropbox', tags: 'dropbox'}
    - {role: 'docker', tags: 'docker'}
    - {role: 'kubectl', tags: 'kubectl'}
    - {role: 'virtualbox', tags: 'virtualbox'}
    - {role: 'minikube', tags: 'minikube'}
    - {role: 'terraform', tags: 'terraform'}
  tasks:
    - name: Install ruby gems for jekyll
      tags: ["jekyll"]
      gem:
        name: "{{ item }}"
        user_install: true
        state: present
      loop:
        - bundler
        - jekyll

    - name: Install minio client(mc)
      tags: ["minio", "mc"]
      get_url:
        url: https://dl.min.io/client/mc/release/linux-amd64/mc
        dest: ~/bin/mc
        mode: "0755"

