---
- name: Update apt cache
  apt: update_cache=true cache_valid_time=86400
  become: yes

- name: "Install common packages"
  apt:
    pkg:
      - autoconf
      - automake
      - curl
      - dirmngr
      - fonts-powerline
      - gpg
      - jq
      - libbz2-dev
      - libffi-dev
      - libncurses-dev
      - libreadline-dev
      - libsqlite3-dev
      - libssl-dev
      - libtool
      - libxslt-dev
      - libyaml-dev
      - net-tools
      - ruby
      - ruby-dev
      - tree
      - unixodbc-dev
      - unzip
      - vim
    state: present
  become: yes

