---
- name: Update apt cache
  apt: update_cache=true cache_valid_time=86400
  become: yes

- name: "Install common packages"
  apt:
    pkg:
      - tree
      - vim
      - net-tools
      - curl
      - fonts-powerline
      - jq
      - ruby
      - ruby-dev
    state: present
  become: yes

