---
- name: Update apt cache (apt).
  apt: update_cache=true cache_valid_time=86400
  when: ansible_os_family == 'Debian'
  become: yes

- name: Ensure git is installed (apt).
  apt:
    name: "{{ git_packages }}"
    state: present
  when:
    - ansible_os_family == 'Debian'
  become: yes

- name: Make .gitconfig is present
  template:
    src: templates/.gitconfig.j2
    dest: ~/.gitconfig
