---
- block:
  - include_tasks: "../../includes/package-with-repo.yml"
    vars:
      apt_source_file: /etc/apt/sources.list.d/virtualbox.list
      apt_source_content: "deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian bionic contrib"
      apt_key: "https://www.virtualbox.org/download/oracle_vbox_2016.asc"
      apt_package: "virtualbox-6.0"
  become: yes