---
- block:
  - name: Add an apt key by id from a keyserver
    apt_key:
      keyserver: pgp.mit.edu
      id: 1C61A2656FB57B7E4DE0F4C1FC918B335044912E

  - include_tasks: "../../includes/package-with-repo.yml"
    vars:
      apt_source_file: /etc/apt/sources.list.d/dropbox.list
      apt_source_content: "deb [arch=i386,amd64] http://linux.dropbox.com/ubuntu bionic main"
      apt_key: ""
      apt_package: "dropbox"
  become: yes